export const CHANGELANGUAGE = 'CHANGELANGUAGE';
export const SEARCH = 'SEARCH';
export const CURRENT_ROUTE = 'CURRENT_ROUTE';
export const PREVIOUS_ROUTE = 'PREVIOUS_ROUTE';
export const SNACKBAR = 'SNACKBAR';
export const SETCLICKEDESTATE = 'SETCLICKEDESTATE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
